### PR TITLE
Add is_current field to genome_release and genome_dataset

### PR DESCRIPTION
**Pull request by james-monkeyshines**
And add release_type field to release table, with possible values of 'nightly_build', 'partial', 'integrated'.

### CODE REVIEW

**Comment by james-monkeyshines** [comment]
Rationale/waffle behind this update: [Linking+genomes+and+releases](https://www.ebi.ac.uk/seqdb/confluence/display/GTI/Linking+genomes+and+releases)

**Comment by james-monkeyshines** [comment]
Schema diagram in Lucid has been updated with these changes.

**Review by marcoooo — COMMENTED** [review]
I thought we said the naming convention would serve this purpose:
- 20220508 == Nightly
- xxx.x == Partial
- xxx == Integrated?

**Comment by james-monkeyshines** [comment]
> I thought we said the naming convention would serve this purpose:
> 
>     * 20220508 == Nightly
>     * xxx.x == Partial
>     * xxx == Integrated?

When I thought about it some more, I decided explicit types would be better; for example, what if vectorbase want integrated release numbers with full stops in them? what if we want to change our naming conventions in a year or two's time? Also, the code/data is more readable/maintainable I think, e.g. if the api request asks for 'partial' releases, we can just pass that straight through as a query parameter, rather than working out a mapping from a release_type to a pattern and then doing something like release_type LIKE '\d{8}'; likewise the results, we can just include that field in the output, rather than parsing the release number and adding a field.

**Review by marcoooo — APPROVED** [review]

**Pull request merged**
